spring.datasource.url=jdbc:mysql://mysql-564d115-bvicam-d8aa.j.aivencloud.com:15694/artgallery?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_XCb5Bv-GnmrWxsIwmDy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true